version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  flask:
    build: ./flask_app
    container_name: flask_dev
    restart: always
    ports:
      - "5000:5000"  # espone Flask sulla porta 5000 dell'host
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=examplepassword
    depends_on:
      - mariadb

volumes:
  mariadb_data: