services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  flask:
    build: .
    container_name: flask_dev
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=examplepassword
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - mariadb
    volumes:
      - ./flask_app:/app  # Monta la cartella locale nel container
